# Generated by Django 3.1.7 on 2021-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
